### ISSUE TITLE
Intern project milestone tracking

### ISSUE THREAD

**Issue by makslevental** [pytorch/PiPPy#277]
- [x] Starter task 1 ([Support ViT models in HF test](https://github.com/pytorch/PiPPy/pull/266)) 
- [x] Starter task 2 ([Collapse sequences of repeating `pipe_split()`](https://github.com/pytorch/PiPPy/pull/267))
- [x] Milestone 1 ([Implement Alpa DP](https://github.com/pytorch/PiPPy/pull/274))
- [ ] Milestone 2 (Test on torchbench models)
- [ ] TBD
